from .customer_interface import ICustomerService
from .inventory_interface import IInventoryService
from .orderdetails_interface import IOrderDetailsService
from .orders_interface import IOrdersService
from .product_interface import IProductService